name: flutter_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  custom_lint: ^0.7.1
  custom_lint_design_system:
    path: custom_lint_design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^26.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/design_system_lint.json
